import 'student.dart';

final List<Student> students = [
  Student(
    name: "Fredrik Strandberg",
    age: 23,
    university: "Kungliga Tekniska Högskolan",
    program: "Industriell Ekonomi",
    year: 5,
    city: "Täby",
    imageName: "fredrik2.png",
    ambassador: false,
  ),
  Student(
    name: "Jesper Senke",
    age: 24,
    university: "Kungliga Tekniska Högskolan",
    program: "Industriell Ekonomi",
    year: 5,
    city: "Vendelsö",
    imageName: "jesper.png",
    ambassador: false,
  ),
  Student(
    name: "Julia Stopner",
    age: 24,
    university: "Kungliga Tekniska Högskolan",
    program: "Industriell Ekonomi",
    year: 5,
    city: "Vasastan",
    imageName: "julia.png",
    ambassador: true,
  ),
  Student(
    name: "Carl-Åke Willberg",
    age: 24,
    university: "Kungliga Tekniska Högskolan",
    program: "Industriell Ekonomi",
    year: 5,
    city: "Täby",
    imageName: "carl-åke.png",
    ambassador: false,
  ),
  Student(
    name: "Lund Lundström",
    age: 21,
    university: "Lunds Universitet",
    program: "Ekonomi",
    year: 1,
    city: "Örebro",
    imageName: "profile.png",
    ambassador: true,
  ),

];
